apiVersion: v1
kind: Service
metadata:
  name: get-message-service
spec:
  selector:
    app: get-message
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer
